# Generated by Django 5.0.7 on 2026-05-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.CharField(choices=[('qrcode', 'Предоплата по QR-коду'), ('card', 'Оплата картой МИР'), ('ofice', 'Постоплата в офисе организации')], max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
